wireplumber.components = [
  {
    name = audio-links.lua, type = script/lua
    provides = custom.audio-links
    requires = [ support.standard-event-source ]
    after = [ monitor.alsa, hooks.node.create-session-item ]
  }
]

wireplumber.profiles = {
  main = {
    custom.audio-links = required
  }
}
