wireplumber.components = [
  {
    name = audio-links.lua, type = script/lua
    provides = custom.audio-links
    requires = [ support.standard-event-source ]
    after = [ monitor.alsa, hooks.node.create-session-item ]
    arguments = {
      links = [
        { output = "gain.output:capture_MONO", input = "scarlett-out:playback_FL" },
        { output = "gain.output:capture_MONO", input = "scarlett-out:playback_FR" },
        { output = "nr_mono.output:capture_MONO", input = "gain.input:playback_MONO" },
        { output = "scarlett-in:capture_FL", input = "nr_mono.input:playback_MONO" },
      ]
    }
  }
]

wireplumber.profiles = {
  main = {
    custom.audio-links = required
  }
}

