wireplumber.components = [
  {
    name = auto-links.lua, type = script/lua
    provides = custom.auto-links
    requires = [ support.standard-event-source ]
    after = [ monitor.alsa, hooks.node.create-session-item ]
    arguments = {
      links = [
        { output = "scarlett-in:capture_FL", input = "eq12b.input:playback_MONO" },
	{ output = "eq12b.output:capture_MONO", input = "nr_mono.input:playback_MONO" },
        { output = "nr_mono.output:capture_MONO", input = "scarlett-out:playback_FL" },
        { output = "nr_mono.output:capture_MONO", input = "scarlett-out:playback_FR" },

        { input = "midi-dump:input", output = "Midi-Bridge:nanoKONTROL2 _ CTRL (capture)" },
        { input = "midi-control:midi_in", output = "Midi-Bridge:nanoKONTROL2 _ CTRL (capture)" },
      ]
    }
  }
]

wireplumber.profiles = {
  main = {
    custom.auto-links = required
  }
}

