monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_(input|output).usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.*"
      }
    ]
    actions = {
      update-props = {
        node.nick = "ucontrol",
	node.name = "ucontrol"
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_output.platform-3f902000.hdmi.hdmi-stereo.*"
      }
    ]
    actions = {
      update-props = {
        node.nick = "system",
	node.name = "system"
      }
    }
  }
]
